const cheerio = require('cheerio');
const JSZip = require('jszip');

const MAX_FILES = 25;
const VALID_PROTOCOLS = ['http:', 'https:'];
function normalizeUrl(input) {
  if (!input || typeof input !== 'string') throw new Error('URL is required.');
  const trimmed = input.trim(); if (!trimmed) throw new Error('URL cannot be empty.');
  let parsed; try { parsed = new URL(trimmed); } catch { try { parsed = new URL(`https://${trimmed}`); } catch { throw new Error('Enter a valid public URL, for example: https://example.com'); } }
  if (!VALID_PROTOCOLS.includes(parsed.protocol)) throw new Error('Only http and https URLs are supported.');
  return parsed.toString();
}
function getFileType(name) { const lower=name.toLowerCase(); if(/\.html?$/.test(lower))return'html'; if(/\.css$/.test(lower))return'css'; if(/\.(js|mjs)$/.test(lower))return'js'; if(/\.tsx?$/.test(lower))return lower.endsWith('tsx')?'tsx':'ts'; if(/\.jsx$/.test(lower))return'jsx'; if(/\.json$/.test(lower))return'json'; if(/\.vue$/.test(lower))return'vue'; if(/\.php$/.test(lower))return'php'; if(/\.py$/.test(lower))return'py'; if(/\.md$/.test(lower))return'md'; if(/\.svg$/.test(lower))return'svg'; if(/\.xml$/.test(lower))return'xml'; if(/\.txt$/.test(lower))return'txt'; return'other'; }
function normalizePathname(name){if(!name||name==='/')return'index.html';return name.replace(/^\/+/, '').replace(/\/+/g,'/');}
function detectTech(html, files){const c=[html,...files.map(f=>f.content||'')].join('\n').toLowerCase();const m=[['HTML5',/<html|<!doctype html>/i],['CSS3',/<style|\.css|backdrop-filter|grid-template/i],['JavaScript',/<script|document\.|window\.|fetch\(|addEventListener/i],['TypeScript',/interface |type [a-z]|tsx|tsconfig|: string/i],['React',/react|createRoot\(|useState\(|jsx-runtime/i],['Next.js',/next/],['Vue',/vue|createApp\(|defineComponent/i],['Angular',/@angular|ng-app|angular/i],['Node.js',/express\(|require\('express'\)|http\.createServer/i],['PHP',/<?php|\$_get|\$_post/i],['Python',/import flask|django|def main\(/i],['Tailwind',/tailwind|className=/i],['Vite',/vite|@vitejs|import.meta.env/i]];const r=m.filter(x=>x[1].test(c)).map(x=>x[0]);return [...new Set(r)].length?[...new Set(r)]:['HTML5'];}
async function fetchText(url){const r=await fetch(url,{headers:{'User-Agent':'XenzioHub/1.0',Accept:'text/html,application/javascript,text/css,*/*;q=0.8'},redirect:'follow'});if(!r.ok)throw new Error(`Unable to fetch resource ${url} (${r.status})`);return {text:await r.text(),contentType:r.headers.get('content-type')||''};}
async function analyzeWebsite(inputUrl){const url=normalizeUrl(inputUrl),base=new URL(url),main=await fetchText(url),$=cheerio.load(main.text),files=[],seen=new Set();const add=(name,content,type,source,size)=>{const n=normalizePathname(name||'index.html');if(seen.has(n))return;seen.add(n);files.push({id:`${source}-${n}`,name:n,type,source,size,content});};add(base.pathname||'/index.html',main.text,'html','entry',main.text.length);const refs=[];$('script[src]').each((_,e)=>refs.push($(e).attr('src')));$('link[rel="stylesheet"][href]').each((_,e)=>refs.push($(e).attr('href')));for(const ref of refs){if(!ref||ref.startsWith('data:')||ref.startsWith('#'))continue;try{const target=new URL(ref,url).toString(),p=new URL(target),type=getFileType(p.pathname);if(type==='other')continue;const response=await fetchText(target),content=response.text;add(normalizePathname(p.pathname.replace(/^\/+/, '')||'index.html'),content,type,'asset',content.length);if(files.length>=MAX_FILES)break;}catch{}}return {url,title:$('title').first().text().trim()||'Untitled Page',metaDescription:$('meta[name="description"]').attr('content')||'No description available',fileCount:files.length,totalSize:files.reduce((s,f)=>s+(f.size||0),0),technologies:detectTech(main.text,files),files:files.map(f=>({...f,typeLabel:f.type.toUpperCase()}))};}
exports.handler=async(event)=>{try{const path=event.path||'';const body=event.body?JSON.parse(event.body):{};if(path.endsWith('/analyze')){const data=await analyzeWebsite(body.url);return{statusCode:200,headers:{'Content-Type':'application/json'},body:JSON.stringify({ok:true,data})};}if(path.endsWith('/download-zip')){const files=body.files||[];if(!Array.isArray(files)||!files.length)throw new Error('No files selected to download.');const zip=new JSZip();files.forEach(f=>{if(f?.name)zip.file(normalizePathname(f.name),f.content||'')});const b=await zip.generateAsync({type:'base64'});return{statusCode:200,isBase64Encoded:true,headers:{'Content-Type':'application/zip','Content-Disposition':'attachment; filename="xenziohub.zip"'},body:b};}return{statusCode:404,body:JSON.stringify({ok:false,message:'Not found'})};}catch(error){return{statusCode:400,headers:{'Content-Type':'application/json'},body:JSON.stringify({ok:false,message:error.message||'Request failed.'})};}};
